# TODO: work in progress
# ansible-galaxy collection install community.general
- name: Add the overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Setting systemctl param to persist across reboot 1/3
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "net.bridge.bridge-nf-call-iptables  = 1"
    state: present
    create: yes

- name: Setting systemctl param to persist across reboot 2/3
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "net.ipv4.ip_forward                 = 1"
    state: present

- name: Setting systemctl param to persist across reboot 3/3
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "net.bridge.bridge-nf-call-ip6tables = 1"
    state: present

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Add an Apt signing key, cri-o 1/2
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ os_id }}/Release.key
    state: present

- name: Add an Apt signing key, cri-o 2/2
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os_id }}/Release.key
    state: present

- name: Add the repository needed to install crio into sources list 1/2
  apt_repository:
    repo: deb [arch={{ ansible_facts['ansible_architecture'] }}] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os_id }}/arm64 /
    state: present

- name: Add the repository needed to install crio into sources list 2/2
  apt_repository:
    repo: deb [arch={{ ansible_facts['ansible_architecture'] }}] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ os_id }}/arm64 /
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install cri-o
  apt:
    name: cri-o
    state: present

- name: Install cri-o-runc
  apt:
    name: cri-o-runc
    state: present

- name: Restart cri-o to reload the new configuration
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: crio