# ansible-galaxy collection install community.general
# Prerequisite
- name: Making sure that "overlay" is present in containerd.conf
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "overlay"
    state: present
    create: yes

- name: Making sure that "br_netfilter" is present in containerd.conf
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "br_netfilter"
    state: present

- name: Add the overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Setting systemctl param to persist across reboot 1/3
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "net.bridge.bridge-nf-call-iptables  = 1"
    state: present
    create: yes

- name: Setting systemctl param to persist across reboot 2/3
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "net.ipv4.ip_forward                 = 1"
    state: present

- name: Setting systemctl param to persist across reboot 3/3
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "net.bridge.bridge-nf-call-ip6tables = 1"
    state: present    

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

# Installation process

- name: Add an Apt signing key, containerd
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the repository needed to install containerd into sources list
  apt_repository:
    repo: deb [arch={{ arch }}] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd.io
    state: present

- name: Set default config for containerd
  shell:
    cmd: containerd config default > /etc/containerd/config.toml

# ^ exactly that
# (\s*) zero to undefine number of spaces
# \1 keep everything there was before the segment I found
- name: Set to use systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    state: present
    regexp: '^(\s*)systemd_cgroup = '
    backrefs: yes
    line: '\1systemd_cgroup = true'

- name: Restart containerd to reload the new configuration
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: containerd